/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_model_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[44] = {12, 12, 0, 0, 0, 0, 6, 11, 13, 14, 15, 16, 19, 24, 29, 3, 4, 5, 6, 7, 8, 3, 5, 6, 7, 8, 6, 7, 0, 1, 2, 3, 10, 11, 3, 4, 5, 9, 11, 3, 4, 5, 9, 10};
static const casadi_int casadi_s4[27] = {12, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s5[3] = {12, 0, 0};

/* quadrotor_model_impl_dae_fun_jac_x_xdot_z:(i0[12],i1[12],i2[4],i3[],i4[],i5[])->(o0[12],o1[12x12,29nz],o2[12x12,12nz],o3[12x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][6] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1]? arg[1][1] : 0;
  a1=arg[0]? arg[0][7] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[1]? arg[1][2] : 0;
  a1=arg[0]? arg[0][8] : 0;
  a0=(a0-a1);
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][3] : 0;
  a1=arg[0]? arg[0][9] : 0;
  a2=arg[0]? arg[0][3] : 0;
  a3=sin(a2);
  a4=arg[0]? arg[0][4] : 0;
  a5=tan(a4);
  a6=(a3*a5);
  a7=arg[0]? arg[0][10] : 0;
  a8=(a6*a7);
  a8=(a1+a8);
  a9=cos(a2);
  a10=tan(a4);
  a11=(a9*a10);
  a12=arg[0]? arg[0][11] : 0;
  a13=(a11*a12);
  a8=(a8+a13);
  a0=(a0-a8);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][4] : 0;
  a8=cos(a2);
  a13=(a8*a7);
  a14=sin(a2);
  a15=(a14*a12);
  a13=(a13-a15);
  a0=(a0-a13);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][5] : 0;
  a13=sin(a2);
  a15=cos(a4);
  a13=(a13/a15);
  a16=(a13*a7);
  a17=cos(a2);
  a18=cos(a4);
  a17=(a17/a18);
  a19=(a17*a12);
  a16=(a16+a19);
  a0=(a0-a16);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][6] : 0;
  a16=sin(a2);
  a19=arg[0]? arg[0][5] : 0;
  a20=sin(a19);
  a21=(a16*a20);
  a22=cos(a2);
  a23=sin(a4);
  a24=(a22*a23);
  a25=cos(a19);
  a26=(a24*a25);
  a21=(a21+a26);
  a26=arg[2]? arg[2][0] : 0;
  a27=arg[2]? arg[2][1] : 0;
  a28=(a26+a27);
  a29=arg[2]? arg[2][2] : 0;
  a28=(a28+a29);
  a30=arg[2]? arg[2][3] : 0;
  a28=(a28+a30);
  a31=2.;
  a28=(a28/a31);
  a21=(a21*a28);
  a0=(a0-a21);
  if (res[0]!=0) res[0][6]=a0;
  a0=arg[1]? arg[1][7] : 0;
  a21=cos(a2);
  a31=sin(a4);
  a32=(a21*a31);
  a33=sin(a19);
  a34=(a32*a33);
  a35=sin(a2);
  a36=cos(a19);
  a37=(a35*a36);
  a34=(a34-a37);
  a34=(a34*a28);
  a0=(a0-a34);
  if (res[0]!=0) res[0][7]=a0;
  a0=arg[1]? arg[1][8] : 0;
  a34=-9.8100000000000005e+00;
  a37=cos(a2);
  a38=cos(a4);
  a39=(a37*a38);
  a39=(a39*a28);
  a34=(a34+a39);
  a0=(a0-a34);
  if (res[0]!=0) res[0][8]=a0;
  a0=arg[1]? arg[1][9] : 0;
  a34=8.3333333333333337e-01;
  a39=2.5000000000000000e-01;
  a40=(a27-a30);
  a40=(a39*a40);
  a41=1.2000000000000000e+00;
  a42=2.2999999999999998e+00;
  a43=(a42*a12);
  a44=(a7*a43);
  a45=(a41*a7);
  a46=(a12*a45);
  a44=(a44-a46);
  a44=(a41-a44);
  a40=(a40+a44);
  a40=(a34*a40);
  a0=(a0-a40);
  if (res[0]!=0) res[0][9]=a0;
  a0=arg[1]? arg[1][10] : 0;
  a40=(a29-a26);
  a39=(a39*a40);
  a40=(a41*a1);
  a44=(a12*a40);
  a46=(a1*a43);
  a44=(a44-a46);
  a44=(a41-a44);
  a39=(a39+a44);
  a39=(a34*a39);
  a0=(a0-a39);
  if (res[0]!=0) res[0][10]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a39=4.3478260869565222e-01;
  a26=(a26-a27);
  a29=(a29-a30);
  a26=(a26+a29);
  a29=(a1*a45);
  a30=(a7*a40);
  a29=(a29-a30);
  a29=(a42-a29);
  a26=(a26+a29);
  a39=(a39*a26);
  a0=(a0-a39);
  if (res[0]!=0) res[0][11]=a0;
  a0=cos(a2);
  a5=(a5*a0);
  a5=(a7*a5);
  a0=sin(a2);
  a10=(a10*a0);
  a10=(a12*a10);
  a5=(a5-a10);
  a5=(-a5);
  if (res[1]!=0) res[1][0]=a5;
  a5=sin(a2);
  a5=(a7*a5);
  a10=cos(a2);
  a10=(a12*a10);
  a5=(a5+a10);
  if (res[1]!=0) res[1][1]=a5;
  a5=cos(a2);
  a5=(a5/a15);
  a5=(a7*a5);
  a10=sin(a2);
  a10=(a10/a18);
  a10=(a12*a10);
  a5=(a5-a10);
  a5=(-a5);
  if (res[1]!=0) res[1][2]=a5;
  a5=cos(a2);
  a20=(a20*a5);
  a5=sin(a2);
  a23=(a23*a5);
  a23=(a25*a23);
  a20=(a20-a23);
  a20=(a28*a20);
  a20=(-a20);
  if (res[1]!=0) res[1][3]=a20;
  a20=sin(a2);
  a31=(a31*a20);
  a31=(a33*a31);
  a20=cos(a2);
  a36=(a36*a20);
  a31=(a31+a36);
  a31=(a28*a31);
  if (res[1]!=0) res[1][4]=a31;
  a2=sin(a2);
  a38=(a38*a2);
  a38=(a28*a38);
  if (res[1]!=0) res[1][5]=a38;
  a38=cos(a4);
  a38=casadi_sq(a38);
  a3=(a3/a38);
  a3=(a7*a3);
  a38=cos(a4);
  a38=casadi_sq(a38);
  a9=(a9/a38);
  a9=(a12*a9);
  a3=(a3+a9);
  a3=(-a3);
  if (res[1]!=0) res[1][6]=a3;
  a15=(a13/a15);
  a3=sin(a4);
  a15=(a15*a3);
  a15=(a7*a15);
  a18=(a17/a18);
  a3=sin(a4);
  a18=(a18*a3);
  a18=(a12*a18);
  a15=(a15+a18);
  a15=(-a15);
  if (res[1]!=0) res[1][7]=a15;
  a15=cos(a4);
  a22=(a22*a15);
  a25=(a25*a22);
  a25=(a28*a25);
  a25=(-a25);
  if (res[1]!=0) res[1][8]=a25;
  a25=cos(a4);
  a21=(a21*a25);
  a33=(a33*a21);
  a33=(a28*a33);
  a33=(-a33);
  if (res[1]!=0) res[1][9]=a33;
  a4=sin(a4);
  a37=(a37*a4);
  a37=(a28*a37);
  if (res[1]!=0) res[1][10]=a37;
  a37=cos(a19);
  a16=(a16*a37);
  a37=sin(a19);
  a24=(a24*a37);
  a16=(a16-a24);
  a16=(a28*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][11]=a16;
  a16=cos(a19);
  a32=(a32*a16);
  a19=sin(a19);
  a35=(a35*a19);
  a32=(a32+a35);
  a28=(a28*a32);
  a28=(-a28);
  if (res[1]!=0) res[1][12]=a28;
  a28=-1.;
  if (res[1]!=0) res[1][13]=a28;
  if (res[1]!=0) res[1][14]=a28;
  if (res[1]!=0) res[1][15]=a28;
  if (res[1]!=0) res[1][16]=a28;
  a28=(a41*a12);
  a28=(a28-a43);
  a28=(a34*a28);
  if (res[1]!=0) res[1][17]=a28;
  a28=0.;
  if (res[1]!=0) res[1][18]=a28;
  a6=(-a6);
  if (res[1]!=0) res[1][19]=a6;
  a8=(-a8);
  if (res[1]!=0) res[1][20]=a8;
  a13=(-a13);
  if (res[1]!=0) res[1][21]=a13;
  a41=(a41*a12);
  a43=(a43-a41);
  a43=(a34*a43);
  if (res[1]!=0) res[1][22]=a43;
  if (res[1]!=0) res[1][23]=a28;
  a11=(-a11);
  if (res[1]!=0) res[1][24]=a11;
  if (res[1]!=0) res[1][25]=a14;
  a17=(-a17);
  if (res[1]!=0) res[1][26]=a17;
  a7=(a42*a7);
  a7=(a7-a45);
  a7=(a34*a7);
  if (res[1]!=0) res[1][27]=a7;
  a42=(a42*a1);
  a40=(a40-a42);
  a34=(a34*a40);
  if (res[1]!=0) res[1][28]=a34;
  a34=1.;
  if (res[2]!=0) res[2][0]=a34;
  if (res[2]!=0) res[2][1]=a34;
  if (res[2]!=0) res[2][2]=a34;
  if (res[2]!=0) res[2][3]=a34;
  if (res[2]!=0) res[2][4]=a34;
  if (res[2]!=0) res[2][5]=a34;
  if (res[2]!=0) res[2][6]=a34;
  if (res[2]!=0) res[2][7]=a34;
  if (res[2]!=0) res[2][8]=a34;
  if (res[2]!=0) res[2][9]=a34;
  if (res[2]!=0) res[2][10]=a34;
  if (res[2]!=0) res[2][11]=a34;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_model_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_model_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_model_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_model_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_model_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_model_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_model_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_model_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_model_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_model_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_model_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s3;
    case 2: return casadi_s4;
    case 3: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_fun_jac_x_xdot_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
