/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_model_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[44] = {12, 12, 0, 0, 0, 0, 6, 11, 13, 14, 15, 16, 19, 24, 29, 3, 4, 5, 6, 7, 8, 3, 5, 6, 7, 8, 6, 7, 0, 1, 2, 3, 10, 11, 3, 4, 5, 9, 11, 3, 4, 5, 9, 10};
static const casadi_int casadi_s4[27] = {12, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s5[27] = {12, 4, 0, 5, 10, 15, 20, 6, 7, 8, 10, 11, 6, 7, 8, 9, 11, 6, 7, 8, 10, 11, 6, 7, 8, 9, 11};
static const casadi_int casadi_s6[3] = {12, 0, 0};

/* quadrotor_model_impl_dae_jac_x_xdot_u_z:(i0[12],i1[12],i2[4],i3[],i4[],i5[])->(o0[12x12,29nz],o1[12x12,12nz],o2[12x4,20nz],o3[12x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][10] : 0;
  a1=arg[0]? arg[0][4] : 0;
  a2=tan(a1);
  a3=arg[0]? arg[0][3] : 0;
  a4=cos(a3);
  a4=(a2*a4);
  a4=(a0*a4);
  a5=arg[0]? arg[0][11] : 0;
  a6=tan(a1);
  a7=sin(a3);
  a7=(a6*a7);
  a7=(a5*a7);
  a4=(a4-a7);
  a4=(-a4);
  if (res[0]!=0) res[0][0]=a4;
  a4=sin(a3);
  a4=(a0*a4);
  a7=cos(a3);
  a7=(a5*a7);
  a4=(a4+a7);
  if (res[0]!=0) res[0][1]=a4;
  a4=cos(a3);
  a7=cos(a1);
  a4=(a4/a7);
  a4=(a0*a4);
  a8=sin(a3);
  a9=cos(a1);
  a8=(a8/a9);
  a8=(a5*a8);
  a4=(a4-a8);
  a4=(-a4);
  if (res[0]!=0) res[0][2]=a4;
  a4=arg[2]? arg[2][0] : 0;
  a8=arg[2]? arg[2][1] : 0;
  a4=(a4+a8);
  a8=arg[2]? arg[2][2] : 0;
  a4=(a4+a8);
  a8=arg[2]? arg[2][3] : 0;
  a4=(a4+a8);
  a8=2.;
  a4=(a4/a8);
  a8=arg[0]? arg[0][5] : 0;
  a10=sin(a8);
  a11=cos(a3);
  a11=(a10*a11);
  a12=cos(a8);
  a13=sin(a1);
  a14=sin(a3);
  a14=(a13*a14);
  a14=(a12*a14);
  a11=(a11-a14);
  a11=(a4*a11);
  a11=(-a11);
  if (res[0]!=0) res[0][3]=a11;
  a11=sin(a8);
  a14=sin(a1);
  a15=sin(a3);
  a15=(a14*a15);
  a15=(a11*a15);
  a16=cos(a8);
  a17=cos(a3);
  a17=(a16*a17);
  a15=(a15+a17);
  a15=(a4*a15);
  if (res[0]!=0) res[0][4]=a15;
  a15=cos(a1);
  a17=sin(a3);
  a17=(a15*a17);
  a17=(a4*a17);
  if (res[0]!=0) res[0][5]=a17;
  a17=sin(a3);
  a18=cos(a1);
  a18=casadi_sq(a18);
  a18=(a17/a18);
  a18=(a0*a18);
  a19=cos(a3);
  a20=cos(a1);
  a20=casadi_sq(a20);
  a20=(a19/a20);
  a20=(a5*a20);
  a18=(a18+a20);
  a18=(-a18);
  if (res[0]!=0) res[0][6]=a18;
  a18=sin(a3);
  a18=(a18/a7);
  a7=(a18/a7);
  a20=sin(a1);
  a7=(a7*a20);
  a7=(a0*a7);
  a20=cos(a3);
  a20=(a20/a9);
  a9=(a20/a9);
  a21=sin(a1);
  a9=(a9*a21);
  a9=(a5*a9);
  a7=(a7+a9);
  a7=(-a7);
  if (res[0]!=0) res[0][7]=a7;
  a7=cos(a3);
  a9=cos(a1);
  a9=(a7*a9);
  a9=(a12*a9);
  a9=(a4*a9);
  a9=(-a9);
  if (res[0]!=0) res[0][8]=a9;
  a9=cos(a3);
  a21=cos(a1);
  a21=(a9*a21);
  a21=(a11*a21);
  a21=(a4*a21);
  a21=(-a21);
  if (res[0]!=0) res[0][9]=a21;
  a21=cos(a3);
  a1=sin(a1);
  a1=(a21*a1);
  a1=(a4*a1);
  if (res[0]!=0) res[0][10]=a1;
  a1=sin(a3);
  a22=cos(a8);
  a22=(a1*a22);
  a7=(a7*a13);
  a13=sin(a8);
  a13=(a7*a13);
  a22=(a22-a13);
  a22=(a4*a22);
  a22=(-a22);
  if (res[0]!=0) res[0][11]=a22;
  a9=(a9*a14);
  a14=cos(a8);
  a14=(a9*a14);
  a22=sin(a3);
  a8=sin(a8);
  a8=(a22*a8);
  a14=(a14+a8);
  a4=(a4*a14);
  a4=(-a4);
  if (res[0]!=0) res[0][12]=a4;
  a4=-1.;
  if (res[0]!=0) res[0][13]=a4;
  if (res[0]!=0) res[0][14]=a4;
  if (res[0]!=0) res[0][15]=a4;
  if (res[0]!=0) res[0][16]=a4;
  a4=8.3333333333333337e-01;
  a14=1.2000000000000000e+00;
  a8=(a14*a5);
  a13=2.2999999999999998e+00;
  a23=(a13*a5);
  a8=(a8-a23);
  a8=(a4*a8);
  if (res[0]!=0) res[0][17]=a8;
  a8=0.;
  if (res[0]!=0) res[0][18]=a8;
  a17=(a17*a2);
  a17=(-a17);
  if (res[0]!=0) res[0][19]=a17;
  a17=cos(a3);
  a17=(-a17);
  if (res[0]!=0) res[0][20]=a17;
  a18=(-a18);
  if (res[0]!=0) res[0][21]=a18;
  a5=(a14*a5);
  a23=(a23-a5);
  a23=(a4*a23);
  if (res[0]!=0) res[0][22]=a23;
  if (res[0]!=0) res[0][23]=a8;
  a19=(a19*a6);
  a19=(-a19);
  if (res[0]!=0) res[0][24]=a19;
  a3=sin(a3);
  if (res[0]!=0) res[0][25]=a3;
  a20=(-a20);
  if (res[0]!=0) res[0][26]=a20;
  a20=(a13*a0);
  a0=(a14*a0);
  a20=(a20-a0);
  a20=(a4*a20);
  if (res[0]!=0) res[0][27]=a20;
  a20=arg[0]? arg[0][9] : 0;
  a14=(a14*a20);
  a13=(a13*a20);
  a14=(a14-a13);
  a4=(a4*a14);
  if (res[0]!=0) res[0][28]=a4;
  a4=1.;
  if (res[1]!=0) res[1][0]=a4;
  if (res[1]!=0) res[1][1]=a4;
  if (res[1]!=0) res[1][2]=a4;
  if (res[1]!=0) res[1][3]=a4;
  if (res[1]!=0) res[1][4]=a4;
  if (res[1]!=0) res[1][5]=a4;
  if (res[1]!=0) res[1][6]=a4;
  if (res[1]!=0) res[1][7]=a4;
  if (res[1]!=0) res[1][8]=a4;
  if (res[1]!=0) res[1][9]=a4;
  if (res[1]!=0) res[1][10]=a4;
  if (res[1]!=0) res[1][11]=a4;
  a4=5.0000000000000000e-01;
  a1=(a1*a10);
  a7=(a7*a12);
  a1=(a1+a7);
  a7=(a4*a1);
  a7=(-a7);
  if (res[2]!=0) res[2][0]=a7;
  a9=(a9*a11);
  a22=(a22*a16);
  a9=(a9-a22);
  a22=(a4*a9);
  a22=(-a22);
  if (res[2]!=0) res[2][1]=a22;
  a21=(a21*a15);
  a15=(a4*a21);
  a15=(-a15);
  if (res[2]!=0) res[2][2]=a15;
  a15=2.0833333333333334e-01;
  if (res[2]!=0) res[2][3]=a15;
  a22=-4.3478260869565222e-01;
  if (res[2]!=0) res[2][4]=a22;
  a16=(a4*a1);
  a16=(-a16);
  if (res[2]!=0) res[2][5]=a16;
  a16=(a4*a9);
  a16=(-a16);
  if (res[2]!=0) res[2][6]=a16;
  a16=(a4*a21);
  a16=(-a16);
  if (res[2]!=0) res[2][7]=a16;
  a16=-2.0833333333333334e-01;
  if (res[2]!=0) res[2][8]=a16;
  a11=4.3478260869565222e-01;
  if (res[2]!=0) res[2][9]=a11;
  a7=(a4*a1);
  a7=(-a7);
  if (res[2]!=0) res[2][10]=a7;
  a7=(a4*a9);
  a7=(-a7);
  if (res[2]!=0) res[2][11]=a7;
  a7=(a4*a21);
  a7=(-a7);
  if (res[2]!=0) res[2][12]=a7;
  if (res[2]!=0) res[2][13]=a16;
  if (res[2]!=0) res[2][14]=a22;
  a1=(a4*a1);
  a1=(-a1);
  if (res[2]!=0) res[2][15]=a1;
  a9=(a4*a9);
  a9=(-a9);
  if (res[2]!=0) res[2][16]=a9;
  a4=(a4*a21);
  a4=(-a4);
  if (res[2]!=0) res[2][17]=a4;
  if (res[2]!=0) res[2][18]=a15;
  if (res[2]!=0) res[2][19]=a11;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_model_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_model_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_model_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_model_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_model_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_model_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_model_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_model_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_model_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_model_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_model_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_model_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
